-- MySQL Script generated by MySQL Workbench
-- Fri Nov 30 16:27:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pharmacy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pharmacy` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pharmacy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `phone_no` VARCHAR(15) NULL,
  `email_id` VARCHAR(50) NULL,
  `address` TEXT NULL,
  `delivery` TINYINT NULL DEFAULT 0,
  `working_time` VARCHAR(50) NULL,
  `logo` VARCHAR(150) NULL,
  `location` VARCHAR(100) NULL,
  `lat` VARCHAR(45) NULL,
  `lng` VARCHAR(45) NULL,
  `status` INT NULL DEFAULT 1 COMMENT '0-Inactive\n1-Active',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pharm_galley`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pharm_galley` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pharm_galley` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pharmacy_has_pharm_galley`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pharmacy_has_pharm_galley` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pharmacy_has_pharm_galley` (
  `pharmacy_id` INT NOT NULL,
  `pharm_galley_id` INT NOT NULL,
  PRIMARY KEY (`pharmacy_id`, `pharm_galley_id`),
  INDEX `fk_pharmacy_has_pharm_galley_pharm_galley1_idx` (`pharm_galley_id` ASC),
  INDEX `fk_pharmacy_has_pharm_galley_pharmacy_idx` (`pharmacy_id` ASC),
  CONSTRAINT `fk_pharmacy_has_pharm_galley_pharmacy`
    FOREIGN KEY (`pharmacy_id`)
    REFERENCES `mydb`.`pharmacy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pharmacy_has_pharm_galley_pharm_galley1`
    FOREIGN KEY (`pharm_galley_id`)
    REFERENCES `mydb`.`pharm_galley` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
